BASIC_SETTING:
    sumo_start_config: ["sumo-gui", "-c", "sumo_network/example42_ex.sumocfg", '--start']
    sumo_start_config_cmd: ["sumo", "-c", "sumo_network/example42_ex.sumocfg", '--start']
    runtime_type: gui
    sumo_dir: './sumo_network/'
    episode: 200
    pre_steps: 200
    simulation_time: 3400

HYPERPARAMETER_SETTING:
    nn_model:
      type: 'MLP'
      units: 50
      active_func: 'sigmoid'
      dropout: 0.2
      loss_func: 'binary_crossentropy'
      batch_size: 64
      epochs: 20
      verbose: 2
      validation_split: 0.2
      learning_rate: 0.01
#      actor_nn: 'mlp'
#      critic_nn: 'cnn'  # eg. mlp\cnn\...
    learning_model:
      model: 'DDPG'
      actor_learning_rate: 0.01
      actor_tau: 0.001
      critic_learning_rate: 0.05
      critic_tau: 0.001
      gamma: 0.98
      maxlen: 500
      entropy_beta: 0.01
    action_selection:
      model: 'eps_greedy'
      epsilon: 1.0
      epsilon_min: 0.01
      epsilon_decay: 0.96


AGENT_ELEMENT_SETTING:
    J1:
      id: J1
      cross_ids: J1  # 路口
      tls_ids: J1  # 信号灯
      states:
          names: [
            '左侧路口北进口直左OCC','左侧路口北进口直左SPEED','左侧路口北进口直左VOL','左侧路口北进口直左JAMLEN',
            '左侧路口南进口直左OCC','左侧路口南进口直左SPEED','左侧路口南进口直左VOL','左侧路口南进口直左JAMLEN',
            '左侧路口西进口直OCC','左侧路口西进口直SPEED','左侧路口西进口直VOL','左侧路口西进口直JAMLEN',
            '左侧路口西进口左OCC','左侧路口西进口左SPEED','左侧路口西进口左VOL','左侧路口西进口左JAMLEN',
            '左侧路口东进口直OCC','左侧路口东进口直SPEED','左侧路口东进口直VOL','左侧路口东进口直JAMLEN',
            '左侧路口东进口左OCC','左侧路口东进口左SPEED','左侧路口东进口左VOL','左侧路口东进口左JAMLEN',
          ]
          func_names: {
            '左侧路口北进口直左OCC': get_occ_on_e2,
            '左侧路口北进口直左SPEED': get_speed_on_e2, 
            '左侧路口北进口直左VOL': get_vol_on_e2,
            '左侧路口北进口直左JAMLEN': get_jam_length_on_e2,

            '左侧路口南进口直左OCC': get_occ_on_e2,
            '左侧路口南进口直左SPEED': get_speed_on_e2, 
            '左侧路口南进口直左VOL': get_vol_on_e2,
            '左侧路口南进口直左JAMLEN': get_jam_length_on_e2,

            '左侧路口西进口直OCC': get_occ_on_e2,
            '左侧路口西进口直SPEED': get_speed_on_e2, 
            '左侧路口西进口直VOL': get_vol_on_e2,
            '左侧路口西进口直JAMLEN': get_jam_length_on_e2,
           
            '左侧路口西进口左OCC': get_occ_on_e2,
            '左侧路口西进口左SPEED': get_speed_on_e2, 
            '左侧路口西进口左VOL': get_vol_on_e2,
            '左侧路口西进口左JAMLEN': get_jam_length_on_e2,

            '左侧路口东进口直OCC': get_occ_on_e2,
            '左侧路口东进口直SPEED': get_speed_on_e2, 
            '左侧路口东进口直VOL': get_vol_on_e2,
            '左侧路口东进口直JAMLEN': get_jam_length_on_e2,

            '左侧路口东进口左OCC': get_occ_on_e2,
            '左侧路口东进口左SPEED': get_speed_on_e2, 
            '左侧路口东进口左VOL': get_vol_on_e2,
            '左侧路口东进口左JAMLEN': get_jam_length_on_e2,
          }
          paras: {
            '左侧路口北进口直左OCC': 'xingminlu_north_entry2',
            '左侧路口北进口直左SPEED': 'xingminlu_north_entry2', 
            '左侧路口北进口直左VOL': 'xingminlu_north_entry2',
            '左侧路口北进口直左JAMLEN': 'xingminlu_north_entry2',

            '左侧路口南进口直左OCC': 'xingminlu_south_entry2',
            '左侧路口南进口直左SPEED': 'xingminlu_south_entry2', 
            '左侧路口南进口直左VOL': 'xingminlu_south_entry2',
            '左侧路口南进口直左JAMLEN': 'xingminlu_south_entry2',

            '左侧路口西进口直OCC': 'yuanlinlu_west_entry2',
            '左侧路口西进口直SPEED': 'yuanlinlu_west_entry2', 
            '左侧路口西进口直VOL': 'yuanlinlu_west_entry2',
            '左侧路口西进口直JAMLEN': 'yuanlinlu_west_entry2',

            '左侧路口西进口左OCC': 'yuanlinlu_west_entry3',
            '左侧路口西进口左SPEED': 'yuanlinlu_west_entry3', 
            '左侧路口西进口左VOL': 'yuanlinlu_west_entry3',
            '左侧路口西进口左JAMLEN': 'yuanlinlu_west_entry3',

            '左侧路口东进口直OCC': 'yuanlinlu_west_mid_exit2',
            '左侧路口东进口直SPEED': 'yuanlinlu_west_mid_exit2', 
            '左侧路口东进口直VOL': 'yuanlinlu_west_mid_exit2',
            '左侧路口东进口直JAMLEN': 'yuanlinlu_west_mid_exit2',

            '左侧路口东进口左OCC': 'yuanlinlu_west_mid_exit3',
            '左侧路口东进口左SPEED': 'yuanlinlu_west_mid_exit3', 
            '左侧路口东进口左VOL': 'yuanlinlu_west_mid_exit3',
            '左侧路口东进口左JAMLEN': 'yuanlinlu_west_mid_exit3',  

          }
      actions:
          names: [ '切换到控制方案0','切换到控制方案1',
                   '切换到控制方案2','切换到控制方案3',
                   '切换到控制方案4','切换到控制方案5',
                   '切换到控制方案6','切换到控制方案7',
                   '切换到控制方案8',
              ]
          func_names: {
              '切换到控制方案0': switch_to_tls_program, 
              '切换到控制方案1': switch_to_tls_program,
              '切换到控制方案2': switch_to_tls_program,
              '切换到控制方案3': switch_to_tls_program,
              '切换到控制方案4': switch_to_tls_program,
              '切换到控制方案5': switch_to_tls_program,
              '切换到控制方案6': switch_to_tls_program,
              '切换到控制方案7': switch_to_tls_program,
              '切换到控制方案8': switch_to_tls_program,
          }
          paras: {
              '切换到控制方案0': ['J1', 'tp_0', 81], # 多个tlsID, 控制方案ID，周期长度
              '切换到控制方案1': ['J1', 'tp_1', 100],
              '切换到控制方案2': ['J1', 'tp_2', 80],
              '切换到控制方案3': ['J1', 'tp_3', 88],
              '切换到控制方案4': ['J1', 'tp_4', 84],
              '切换到控制方案5': ['J1', 'tp_5', 75],
              '切换到控制方案6': ['J1', 'tp_6', 34],
              '切换到控制方案7': ['J1', 'tp_7', 62],
              '切换到控制方案8': ['J1', 'tp_8', 135],
          }
      rewards:
          names: '路口总延误'
          func_names: {
              '路口总延误': get_interval_time_loss_on_e3_as_reward
          }
          paras: {
              '路口总延误': 'LEFT_e3_det'              
          }
    
    J3:
      id: J3
      cross_ids: J3
      tls_ids: J3
      states:
          names: [
            '中间路口北进口直OCC','中间路口北进口直SPEED','中间路口北进口直VOL','中间路口北进口直JAMLEN',
            '中间路口北进口左OCC','中间路口北进口左SPEED','中间路口北进口左VOL','中间路口北进口左JAMLEN',
            '中间路口南进口直OCC','中间路口南进口直SPEED','中间路口南进口直VOL','中间路口南进口直JAMLEN',
            '中间路口南进口左OCC','中间路口南进口左SPEED','中间路口南进口左VOL','中间路口南进口左JAMLEN',
            '中间路口西进口直OCC','中间路口西进口直SPEED','中间路口西进口直VOL','中间路口西进口直JAMLEN',
            '中间路口西进口左OCC','中间路口西进口左SPEED','中间路口西进口左VOL','中间路口西进口左JAMLEN',
            '中间路口东进口直OCC','中间路口东进口直SPEED','中间路口东进口直VOL','中间路口东进口直JAMLEN',
            '中间路口东进口左OCC','中间路口东进口左SPEED','中间路口东进口左VOL','中间路口东进口左JAMLEN',
          ]
          func_names: {
            '中间路口北进口直OCC': get_occ_on_e2,
            '中间路口北进口直SPEED': get_speed_on_e2, 
            '中间路口北进口直VOL': get_vol_on_e2,
            '中间路口北进口直JAMLEN': get_jam_length_on_e2,

            '中间路口北进口左OCC': get_occ_on_e2,
            '中间路口北进口左SPEED': get_speed_on_e2, 
            '中间路口北进口左VOL': get_vol_on_e2,
            '中间路口北进口左JAMLEN': get_jam_length_on_e2,

            '中间路口南进口直OCC': get_occ_on_e2,
            '中间路口南进口直SPEED': get_speed_on_e2, 
            '中间路口南进口直VOL': get_vol_on_e2,
            '中间路口南进口直JAMLEN': get_jam_length_on_e2,

            '中间路口南进口左OCC': get_occ_on_e2,
            '中间路口南进口左SPEED': get_speed_on_e2, 
            '中间路口南进口左VOL': get_vol_on_e2,
            '中间路口南进口左JAMLEN': get_jam_length_on_e2,

            '中间路口西进口直OCC': get_occ_on_e2,
            '中间路口西进口直SPEED': get_speed_on_e2, 
            '中间路口西进口直VOL': get_vol_on_e2,
            '中间路口西进口直JAMLEN': get_jam_length_on_e2,
           
            '中间路口西进口左OCC': get_occ_on_e2,
            '中间路口西进口左SPEED': get_speed_on_e2, 
            '中间路口西进口左VOL': get_vol_on_e2,
            '中间路口西进口左JAMLEN': get_jam_length_on_e2,

            '中间路口东进口直OCC': get_occ_on_e2,
            '中间路口东进口直SPEED': get_speed_on_e2, 
            '中间路口东进口直VOL': get_vol_on_e2,
            '中间路口东进口直JAMLEN': get_jam_length_on_e2,

            '中间路口东进口左OCC': get_occ_on_e2,
            '中间路口东进口左SPEED': get_speed_on_e2, 
            '中间路口东进口左VOL': get_vol_on_e2,
            '中间路口东进口左JAMLEN': get_jam_length_on_e2,
          }
          paras: {
            '中间路口北进口直OCC': 'fukanglu_north_entry2',
            '中间路口北进口直SPEED': 'fukanglu_north_entry2', 
            '中间路口北进口直VOL': 'fukanglu_north_entry2',
            '中间路口北进口直JAMLEN': 'fukanglu_north_entry2',

            '中间路口北进口左OCC': 'fukanglu_north_entry3',
            '中间路口北进口左SPEED': 'fukanglu_north_entry3', 
            '中间路口北进口左VOL': 'fukanglu_north_entry3',
            '中间路口北进口左JAMLEN': 'fukanglu_north_entry3',

            '中间路口南进口直OCC': 'fukanglu_south_entry2',
            '中间路口南进口直SPEED': 'fukanglu_south_entry2', 
            '中间路口南进口直VOL': 'fukanglu_south_entry2',
            '中间路口南进口直JAMLEN': 'fukanglu_south_entry2',

            '中间路口南进口左OCC': 'fukanglu_south_entry3',
            '中间路口南进口左SPEED': 'fukanglu_south_entry3', 
            '中间路口南进口左VOL': 'fukanglu_south_entry3',
            '中间路口南进口左JAMLEN': 'fukanglu_south_entry3',

            '中间路口西进口直OCC': 'yuanlinlu_west_mid_entry2',
            '中间路口西进口直SPEED': 'yuanlinlu_west_mid_entry2', 
            '中间路口西进口直VOL': 'yuanlinlu_west_mid_entry2',
            '中间路口西进口直JAMLEN': 'yuanlinlu_west_mid_entry2',

            '中间路口西进口左OCC': 'yuanlinlu_west_mid_entry3',
            '中间路口西进口左SPEED': 'yuanlinlu_west_mid_entry3', 
            '中间路口西进口左VOL': 'yuanlinlu_west_mid_entry3',
            '中间路口西进口左JAMLEN': 'yuanlinlu_west_mid_entry3',

            '中间路口东进口直OCC': 'yuanlinlu_east_mid_exit2',
            '中间路口东进口直SPEED': 'yuanlinlu_east_mid_exit2', 
            '中间路口东进口直VOL': 'yuanlinlu_east_mid_exit2',
            '中间路口东进口直JAMLEN': 'yuanlinlu_east_mid_exit2',

            '中间路口东进口左OCC': 'yuanlinlu_east_mid_exit3',
            '中间路口东进口左SPEED': 'yuanlinlu_east_mid_exit3', 
            '中间路口东进口左VOL': 'yuanlinlu_east_mid_exit3',
            '中间路口东进口左JAMLEN': 'yuanlinlu_east_mid_exit3',  

          }
      actions:
          names: [ '切换到控制方案0','切换到控制方案1',
                   '切换到控制方案2','切换到控制方案3',
                   '切换到控制方案4','切换到控制方案5',
                   '切换到控制方案6','切换到控制方案7',
                   '切换到控制方案8',
              ]
          func_names: {
              '切换到控制方案0': switch_to_tls_program, 
              '切换到控制方案1': switch_to_tls_program,
              '切换到控制方案2': switch_to_tls_program,
              '切换到控制方案3': switch_to_tls_program,
              '切换到控制方案4': switch_to_tls_program,
              '切换到控制方案5': switch_to_tls_program,
              '切换到控制方案6': switch_to_tls_program,
              '切换到控制方案7': switch_to_tls_program,
              '切换到控制方案8': switch_to_tls_program,
          }
          paras: {
              '切换到控制方案0': ['J3', 'tp_0', 145], # 多个tlsID, 控制方案ID，周期长度
              '切换到控制方案1': ['J3', 'tp_1', 175],
              '切换到控制方案2': ['J3', 'tp_2', 190],
              '切换到控制方案3': ['J3', 'tp_3', 240],
              '切换到控制方案4': ['J3', 'tp_4', 190],
              '切换到控制方案5': ['J3', 'tp_5', 250],
              '切换到控制方案6': ['J3', 'tp_6', 160],
              '切换到控制方案7': ['J3', 'tp_7', 200],
              '切换到控制方案8': ['J3', 'tp_8', 200],
          }
      rewards:
          names: '路口总延误'
          func_names: {
              '路口总延误': get_interval_time_loss_on_e3_as_reward
          }
          paras: {
              '路口总延误': 'MID_e3_det'              
          }

    J6:
      id: J6
      cross_ids: J6
      tls_ids: J6
      states:
          names: [
            '右侧路口北进口直左OCC','右侧路口北进口直左SPEED','右侧路口北进口直左VOL','右侧路口北进口直左JAMLEN',
            '右侧路口南进口直左OCC','右侧路口南进口直左SPEED','右侧路口南进口直左VOL','右侧路口南进口直左JAMLEN',
            '右侧路口西进口直OCC','右侧路口西进口直SPEED','右侧路口西进口直VOL','右侧路口西进口直JAMLEN',
            '右侧路口西进口左OCC','右侧路口西进口左SPEED','右侧路口西进口左VOL','右侧路口西进口左JAMLEN',
            '右侧路口东进口直OCC','右侧路口东进口直SPEED','右侧路口东进口直VOL','右侧路口东进口直JAMLEN',
            '右侧路口东进口左OCC','右侧路口东进口左SPEED','右侧路口东进口左VOL','右侧路口东进口左JAMLEN',
          ]
          func_names: {
            '右侧路口北进口直左OCC': get_occ_on_e2,
            '右侧路口北进口直左SPEED': get_speed_on_e2, 
            '右侧路口北进口直左VOL': get_vol_on_e2,
            '右侧路口北进口直左JAMLEN': get_jam_length_on_e2,

            '右侧路口南进口直左OCC': get_occ_on_e2,
            '右侧路口南进口直左SPEED': get_speed_on_e2, 
            '右侧路口南进口直左VOL': get_vol_on_e2,
            '右侧路口南进口直左JAMLEN': get_jam_length_on_e2,

            '右侧路口西进口直OCC': get_occ_on_e2,
            '右侧路口西进口直SPEED': get_speed_on_e2, 
            '右侧路口西进口直VOL': get_vol_on_e2,
            '右侧路口西进口直JAMLEN': get_jam_length_on_e2,
           
            '右侧路口西进口左OCC': get_occ_on_e2,
            '右侧路口西进口左SPEED': get_speed_on_e2, 
            '右侧路口西进口左VOL': get_vol_on_e2,
            '右侧路口西进口左JAMLEN': get_jam_length_on_e2,

            '右侧路口东进口直OCC': get_occ_on_e2,
            '右侧路口东进口直SPEED': get_speed_on_e2, 
            '右侧路口东进口直VOL': get_vol_on_e2,
            '右侧路口东进口直JAMLEN': get_jam_length_on_e2,

            '右侧路口东进口左OCC': get_occ_on_e2,
            '右侧路口东进口左SPEED': get_speed_on_e2, 
            '右侧路口东进口左VOL': get_vol_on_e2,
            '右侧路口东进口左JAMLEN': get_jam_length_on_e2,
          }
          paras: {
            '右侧路口北进口直左OCC': 'feitianlu_north_entry2',
            '右侧路口北进口直左SPEED': 'feitianlu_north_entry2', 
            '右侧路口北进口直左VOL': 'feitianlu_north_entry2',
            '右侧路口北进口直左JAMLEN': 'feitianlu_north_entry2',

            '右侧路口南进口直左OCC': 'feitianlu_south_entry2',
            '右侧路口南进口直左SPEED': 'feitianlu_south_entry2', 
            '右侧路口南进口直左VOL': 'feitianlu_south_entry2',
            '右侧路口南进口直左JAMLEN': 'feitianlu_south_entry2',

            '右侧路口西进口直OCC': 'yuanlinlu_east_mid_exit2',
            '右侧路口西进口直SPEED': 'yuanlinlu_east_mid_exit2', 
            '右侧路口西进口直VOL': 'yuanlinlu_east_mid_exit2',
            '右侧路口西进口直JAMLEN': 'yuanlinlu_east_mid_exit2',

            '右侧路口西进口左OCC': 'yuanlinlu_east_mid_exit3',
            '右侧路口西进口左SPEED': 'yuanlinlu_east_mid_exit3', 
            '右侧路口西进口左VOL': 'yuanlinlu_east_mid_exit3',
            '右侧路口西进口左JAMLEN': 'yuanlinlu_east_mid_exit3',

            '右侧路口东进口直OCC': 'yuanlinlu_east_entry2',
            '右侧路口东进口直SPEED': 'yuanlinlu_east_entry2', 
            '右侧路口东进口直VOL': 'yuanlinlu_east_entry2',
            '右侧路口东进口直JAMLEN': 'yuanlinlu_east_entry2',

            '右侧路口东进口左OCC': 'yuanlinlu_east_entry3',
            '右侧路口东进口左SPEED': 'yuanlinlu_east_entry3', 
            '右侧路口东进口左VOL': 'yuanlinlu_east_entry3',
            '右侧路口东进口左JAMLEN': 'yuanlinlu_east_entry3',  

          }
      actions:
          names: [ '切换到控制方案0','切换到控制方案1',
                   '切换到控制方案2','切换到控制方案3',
                   '切换到控制方案4','切换到控制方案5',
                   '切换到控制方案6','切换到控制方案7',
                   '切换到控制方案8',
              ]
          func_names: {
              '切换到控制方案0': switch_to_tls_program, 
              '切换到控制方案1': switch_to_tls_program,
              '切换到控制方案2': switch_to_tls_program,
              '切换到控制方案3': switch_to_tls_program,
              '切换到控制方案4': switch_to_tls_program,
              '切换到控制方案5': switch_to_tls_program,
              '切换到控制方案6': switch_to_tls_program,
              '切换到控制方案7': switch_to_tls_program,
              '切换到控制方案8': switch_to_tls_program,
          }
          paras: {
              '切换到控制方案0': ['J6', 'tp_0', 145], # tlsID, 控制方案ID，周期长度
              '切换到控制方案1': ['J6', 'tp_1', 175],
              '切换到控制方案2': ['J6', 'tp_2', 190],
              '切换到控制方案3': ['J6', 'tp_3', 240],
              '切换到控制方案4': ['J6', 'tp_4', 190],
              '切换到控制方案5': ['J6', 'tp_5', 250],
              '切换到控制方案6': ['J6', 'tp_6', 160],
              '切换到控制方案7': ['J6', 'tp_7', 200],
              '切换到控制方案8': ['J6', 'tp_8', 200],
          }
      rewards:
          names: '路口总延误'
          func_names: {
              '路口总延误': get_interval_time_loss_on_e3_as_reward
          }
          paras: {
              '路口总延误': 'RIGHT_e3_det'              
          }